name: C++ TCP Chat CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Build TCP Server
        run: g++ -o tcpServer tcpServer.cpp -lpthread

      - name: Build TCP Client
        run: g++ -o tcpClient tcpClient.cpp

      - name: Run integration test
        run: |
          # Start server in background
          ./tcpServer > server.log 2>&1 &
          SERVER_PID=$!
          sleep 2

          # Simulate a conversation
          printf "hello\nexit\n" | ./tcpClient TestClient 54550 > client.log 2>&1 || true

          # Stop server
          kill $SERVER_PID || true
          sleep 1

          echo "==== SERVER LOG ===="
          cat server.log
          echo "==== CLIENT LOG ===="
          cat client.log

          # Check if "From Server:" line contains "hello"
          if grep -q "From Server: hello" client.log; then
            echo "✅ Test passed: client received echo from server"
          else
            echo "❌ Test failed: client did not receive expected echo"
            exit 1
          fi
