name: C++ TCP Chat CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Build TCP Server
        run: g++ -o tcpServer tcpServer.cpp -lpthread

      - name: Build TCP Client
        run: g++ -o tcpClient tcpClient.cpp

      - name: Run integration test with two clients
        run: |
          # Start server in background
          ./tcpServer > server.log 2>&1 &
          SERVER_PID=$!
          sleep 2

          # Start first client (Alice)
          printf "hello from Alice\nexit\n" | ./tcpClient Alice 54550 > client1.log 2>&1 &
          CLIENT1_PID=$!

          # Start second client (Bob)
          printf "hello from Bob\nexit\n" | ./tcpClient Bob 54550 > client2.log 2>&1 &
          CLIENT2_PID=$!

          # Wait for both clients to finish
          wait $CLIENT1_PID
          wait $CLIENT2_PID

          # Stop server
          kill $SERVER_PID || true
          sleep 1

          echo "==== SERVER LOG ===="
          cat server.log
          echo "==== CLIENT 1 LOG (Alice) ===="
          cat client1.log
          echo "==== CLIENT 2 LOG (Bob) ===="
          cat client2.log

          # Verify both clients got echoes back
          if grep -q "From Server: hello from Alice" client1.log && \
             grep -q "From Server: hello from Bob" client2.log; then
            echo "✅ Test passed: both clients received echoes"
          else
            echo "❌ Test failed: one or both clients did not receive echo"
            exit 1
          fi
