name: C++ TCP Chat CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:   # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies (just g++)
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++

      # Build server
      - name: Build TCP Server
        run: g++ -o tcpServer tcpServer.cpp -lpthread

      # Build client
      - name: Build TCP Client
        run: g++ -o tcpClient tcpClient.cpp

      # Run a basic check
      - name: Verify binaries
        run: |
          ls -lh tcpServer tcpClient
